<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\AdminController::addToGroup' => array('privates', '.service_locator.so3FJk6', 'get_ServiceLocator_So3FJk6Service.php', true),
    'App\\Controller\\AdminController::addUserToGroup' => array('privates', '.service_locator.vKhz1wp', 'get_ServiceLocator_VKhz1wpService.php', true),
    'App\\Controller\\AdminController::index' => array('privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true),
    'App\\Controller\\CategoryController::delete' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CategoryController::edit' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CategoryController::index' => array('privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true),
    'App\\Controller\\CategoryController::show' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CustomerController::delete' => array('privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true),
    'App\\Controller\\CustomerController::edit' => array('privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true),
    'App\\Controller\\CustomerController::index' => array('privates', '.service_locator.itO3VKs', 'get_ServiceLocator_ItO3VKsService.php', true),
    'App\\Controller\\CustomerController::show' => array('privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true),
    'App\\Controller\\SecurityController::login' => array('privates', '.service_locator.XucFk1g', 'get_ServiceLocator_XucFk1gService.php', true),
    'App\\Controller\\AdminController:addToGroup' => array('privates', '.service_locator.so3FJk6', 'get_ServiceLocator_So3FJk6Service.php', true),
    'App\\Controller\\AdminController:addUserToGroup' => array('privates', '.service_locator.vKhz1wp', 'get_ServiceLocator_VKhz1wpService.php', true),
    'App\\Controller\\AdminController:index' => array('privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true),
    'App\\Controller\\CategoryController:delete' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CategoryController:edit' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CategoryController:index' => array('privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true),
    'App\\Controller\\CategoryController:show' => array('privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true),
    'App\\Controller\\CustomerController:delete' => array('privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true),
    'App\\Controller\\CustomerController:edit' => array('privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true),
    'App\\Controller\\CustomerController:index' => array('privates', '.service_locator.itO3VKs', 'get_ServiceLocator_ItO3VKsService.php', true),
    'App\\Controller\\CustomerController:show' => array('privates', '.service_locator.ViwMQSq', 'get_ServiceLocator_ViwMQSqService.php', true),
    'App\\Controller\\SecurityController:login' => array('privates', '.service_locator.XucFk1g', 'get_ServiceLocator_XucFk1gService.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
