<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XucFk1g' shared service.

return $this->privates['.service_locator.XucFk1g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'authenticationUtils' => array('services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true),
    'customerRepository' => array('privates', 'App\\Repository\\CustomerRepository', 'getCustomerRepositoryService.php', true),
));
