<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1lGZZG3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1lGZZG3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1lGZZG3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1lGZZG3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container1lGZZG3\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '1lGZZG3',
    'container.build_id' => 'd04e3c58',
    'container.build_time' => 1546870113,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1lGZZG3');
